# Generated by Django 4.1.2 on 2022-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
