# Generated by Django 4.1.2 on 2022-10-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categori',
            new_name='about',
        ),
    ]
